{{- if .Values.mediator.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: mediator
spec:
  template:
    metadata:
      labels:
        app: mediator
    spec:
      restartPolicy: Never
      containers:
      - name: mediator-container
        image: {{ .Values.mediator.image.repository }}:{{ .Values.mediator.image.tag }}
        imagePullPolicy: {{ .Values.mediator.image.pullPolicy }}
        env:
        {{- range $key, $value := .Values.mediator.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mediator.existingSecret }}
              key: {{ .Values.mediator.redisPasswordKey }}
        - name: INFLUX_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mediator.existingSecret }}
              key: {{ .Values.mediator.influxTokenKey }}
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 80
{{- end }}
